[build]
  command = "npm run build" # Build işlemi
  functions = "netlify/functions" # Fonksiyonların bulunduğu dizin
  publish = "." # Statik dosyalarınızın bulunduğu dizin (kök dizin)

[functions]
  node_bundler = "esbuild" # Node.js paket yöneticisi
  included_files = ["**/*.html", "**/*.css", "**/*.js"] # Fonksiyonlara dahil edilecek dosyalar

# Ana sayfa yönlendirmesi
[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200
  force = true

# playGame fonksiyonu için yönlendirme
[[redirects]]
  from = "/play"
  to = "/.netlify/functions/playGame"
  status = 200
  force = true

# Diğer tüm istekler için yönlendirme
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true