[build]
  command = "npm run build" # Eğer bir build işleminiz varsa
  functions = ".netlify/functions" # Fonksiyonların bulunduğu dizin
  publish = "." # Statik dosyalarınızın bulunduğu dizin (kök dizin)

[functions]
  node_bundler = "esbuild" # Node.js paket yöneticisi
  included_files = ["**/*.html", "**/*.css", "**/*.js"] # Fonksiyonlara dahil edilecek dosyalar

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true